### ISSUE TITLE
Running from source according to README commands fails

### ISSUE THREAD

**Issue by faustbrian** [LiskHQ/lisk-desktop#3694]
Following the instructions on `development` to run the wallet from source seems to fail. I tried a combination of all the build, electron and dev commands and all of them result in build errors.

What commands and branch should be used to run what will eventually end up in the RC tags?

**Environment**
The environment shows node 14 but I also tried node 12 and 16 to no avail.
```
  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 16.51 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /var/folders/0p/9pg3crh13615ccfsklnkz5z80000gn/T/fnm_multishells/30193_1626398373037/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /var/folders/0p/9pg3crh13615ccfsklnkz5z80000gn/T/fnm_multishells/30193_1626398373037/bin/npm
```

**Error**
```
❯ npm install && npm run dev

> Lisk@2.0.0-rc.2 dev /Users/brian/lisk-desktop
> DEBUG=true NACL_FAST=disable && webpack serve --config ./config/webpack.config.dev

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from src
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: assets by info 13.2 MiB [immutable]
  assets by path *.js 13.2 MiB
    assets by chunk 8.44 MiB (id hint: vendors) 6 assets
    asset bundle.app.424313a0c1ff2f023305.js 4.68 MiB [emitted] [immutable] (name: app) 1 related asset
    asset bundle.head.db30759550d037fcddbd.js 47.2 KiB [emitted] [immutable] (name: head) 1 related asset
  assets by path src/assets/fonts/iconfont/ 26.7 KiB
    asset src/assets/fonts/iconfont/icons-212f81.ttf 17.2 KiB [emitted] [immutable] [from: src/assets/fonts/iconfont/icons.ttf] (auxiliary name: app)
    asset src/assets/fonts/iconfont/icons-5bcee6.woff 9.52 KiB [emitted] [immutable] [from: src/assets/fonts/iconfont/icons.woff] (auxiliary name: app)
assets by path *.css 777 KiB
  asset app.css 738 KiB [emitted] (name: app) 1 related asset
  asset vendors-node_modules_babel_runtime_regenerator_index_js-node_modules_liskhq_lisk-client_dist--458ce8.css 38 KiB [emitted] (id hint: vendors) 1 related asset
  asset head.css 1.45 KiB [emitted] (name: head) 1 related asset
asset index.html 4.75 KiB [emitted]
Entrypoint app 12.3 MiB (11.1 MiB) = bundle.vendors-node_modules_mini-css-extract-plugin_dist_hmr_hotModuleReplacement_js-node_modules_we-7d1abe.d6f2f449f8f04fc5df59.js 357 KiB vendors-node_modules_babel_runtime_regenerator_index_js-node_modules_liskhq_lisk-client_dist--458ce8.css 38 KiB bundle.vendors-node_modules_babel_runtime_regenerator_index_js-node_modules_liskhq_lisk-client_dist--458ce8.ef8f9a8a49d15da7aff4.js 6.51 MiB app.css 738 KiB bundle.app.424313a0c1ff2f023305.js 4.68 MiB 7 auxiliary assets
Entrypoint head 406 KiB (458 KiB) = bundle.vendors-node_modules_mini-css-extract-plugin_dist_hmr_hotModuleReplacement_js-node_modules_we-7d1abe.d6f2f449f8f04fc5df59.js 357 KiB head.css 1.45 KiB bundle.head.db30759550d037fcddbd.js 47.2 KiB 3 auxiliary assets
runtime modules 65.9 KiB 34 modules
orphan modules 26.3 KiB [orphan] 7 modules
javascript modules 10.7 MiB 1974 modules
css modules 777 KiB
  modules by path ./src/components/ 730 KiB 82 modules
  modules by path ./node_modules/ 37.9 KiB 3 modules
  css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].use[1]!./src/assets/css/styles.head.css 1.41 KiB [code generated]
  css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].use[1]!./node_modules/postcss-loader/src/index.js??ruleSet[1].rules[5].use[2]!./src/app/variables.css 7.88 KiB [code generated]
json modules 362 KiB
  modules by path ./node_modules/ 140 KiB 12 modules
  modules by path ./src/assets/animations/*.json 182 KiB 4 modules
  ./i18n/locales/en/common.json 39.8 KiB [built] [code generated]

WARNING in ./src/components/shared/registerMultiStep/element.js 28:19-42
Module not found: Error: Can't resolve 'react-native' in '/Users/brian/lisk-desktop/src/components/shared/registerMultiStep'
 @ ./src/components/shared/registerMultiStep/index.js 36:0-36 177:46-53
 @ ./src/components/screens/register/register.js 50:0-50 122:42-51
 @ ./src/components/screens/register/index.js 14:0-34 23:69-77
 @ ./src/routesMap.js 21:0-41 48:12-20
 @ ./src/app/index.js 41:0-37 108:17-26
 @ ./src/main.js 20:0-24 50:33-36 53:29-57:3 53:2-57:4 54:28-51

ERROR in ./node_modules/bitcore-mnemonic/lib/errors.js 18:17-53
Module not found: Error: Can't resolve 'bitcore-lib' in '/Users/brian/lisk-desktop/node_modules/bitcore-mnemonic/lib'
 @ ./node_modules/bitcore-mnemonic/lib/mnemonic.js 9:13-32
 @ ./node_modules/bitcore-mnemonic/index.js 1:0-42
 @ ./src/utils/passphrase.js 27:15-42
 @ ./src/components/screens/register/register.js 46:0-55 79:57-75
 @ ./src/components/screens/register/index.js 14:0-34 23:69-77
 @ ./src/routesMap.js 21:0-41 48:12-20
 @ ./src/app/index.js 41:0-37 108:17-26
 @ ./src/main.js 20:0-24 50:33-36 53:29-57:3 53:2-57:4 54:28-51

ERROR in ./node_modules/bitcore-mnemonic/lib/mnemonic.js 3:14-36
Module not found: Error: Can't resolve 'bitcore-lib' in '/Users/brian/lisk-desktop/node_modules/bitcore-mnemonic/lib'
 @ ./node_modules/bitcore-mnemonic/index.js 1:0-42
 @ ./src/utils/passphrase.js 27:15-42
 @ ./src/components/screens/register/register.js 46:0-55 79:57-75
 @ ./src/components/screens/register/index.js 14:0-34 23:69-77
 @ ./src/routesMap.js 21:0-41 48:12-20
 @ ./src/app/index.js 41:0-37 108:17-26
 @ ./src/main.js 20:0-24 50:33-36 53:29-57:3 53:2-57:4 54:28-51

ERROR in ./src/app/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../assets/fonts/gilroy/gilroy-bold.woff2' in '/Users/brian/lisk-desktop/src/app'
    at finishWithoutResolve (/Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/brian/lisk-desktop/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/brian/lisk-desktop/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/brian/lisk-desktop/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/brian/lisk-desktop/node_modules/enhanced-resolve/lib/forEachBail.js:16:12
    at processResult (/Users/brian/lisk-desktop/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Users/brian/lisk-desktop/node_modules/webpack/lib/NormalModule.js:692:5
    at /Users/brian/lisk-desktop/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/brian/lisk-desktop/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/brian/lisk-desktop/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/brian/lisk-desktop/node_modules/css-loader/dist/index.js:154:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 @ ./src/app/index.js 43:0-31 87:15-36 88:20-36 89:19-35 95:25-43 95:66-79 99:25-43 99:57-71
 @ ./src/main.js 20:0-24 50:33-36 53:29-57:3 53:2-57:4 54:28-51

ERROR in ./node_modules/react-chartjs-2/es/index.js 13:0-29
Module not found: Error: Can't resolve 'chart.js' in '/Users/brian/lisk-desktop/node_modules/react-chartjs-2/es'
 @ ./src/components/toolbox/charts/index.js 12:0-54 26:42-46 43:42-45 60:42-50
 @ ./src/components/screens/monitor/network/overview/index.js 23:0-48 93:38-51 105:38-51 154:38-51 166:38-51 216:38-51 225:38-51
 @ ./src/components/screens/monitor/network/index.js 38:0-34 95:88-96
 @ ./src/routesMap.js 19:0-54 55:11-25
 @ ./src/app/index.js 41:0-37 108:17-26
 @ ./src/main.js 20:0-24 50:33-36 53:29-57:3 53:2-57:4 54:28-51

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

3 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.24.2 compiled with 6 errors and 2 warnings in 87520 ms
ℹ ｢wdm｣: Failed to compile.
```

**Comment by reyraa** [comment]
Hi.
Please read [instructions to replace the commercial fonts](https://github.com/LiskHQ/lisk-desktop#using-commercial-fonts).

**Comment by faustbrian** [comment]
I've read that and it doesn't resolve the issue because there's more issues with libraries that don't seem to be available or properly linked.

**Comment by reyraa** [comment]
`Chartjs` has a breaking change in the latest minor version. Try installing dependecies using `npm ci` (not `npm i` or `npm install`).
