### ISSUE TITLE
Fix unstable e2e tests

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk-desktop#4058]
### Expected behavior

Ensure all e2e tests are stable and consistently passing.

### Actual behavior

Following feature tests are failing/unstable

- Send.Feature

for more details check https://github.com/LiskHQ/lisk-desktop/issues/4058#issuecomment-1008894129

### Steps to reproduce

Check CI for unstable tests

### Which version(s) does this affect? (Environment, OS, etc...)
2.2.0

**Comment by ManuGowda** [comment]
```
 2 passing (52s)

  2 failing



  1) Send

       Error message is shown if transfer tx fails:

     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.open-send-dialog`, but never found it.

      at Context.eval (https://jenkins.lisk.com/__cypress/tests?p=features/send.feature:42962:6)

      at Context.resolveAndRunStepDefinition (https://jenkins.lisk.com/__cypress/tests?p=features/send.feature:11248:29)

      at Context.eval (https://jenkins.lisk.com/__cypress/tests?p=features/send.feature:10569:35)



  2) Send

       "after each" hook for "Launch protocol prefills fields  - from logged out state":

     Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.



  > Account lskdxc4ta5j43jp9ro3f8zqbxta9fn6jwzjucw7yt not found.



When Cypress detects uncaught errors originating from your application it will automatically fail the current test.



This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.



https://on.cypress.io/uncaught-exception-from-application



Because this error occurred during a `after each` hook we are skipping all of the remaining tests.

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2641357

      at c (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2790943)

      at Generator._invoke (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2790731)

      at Generator.next (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2791372)

      at i (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2639474)

      at a (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2641592)
```

```
  2 passing (46s)

  2 failing



  1) Vote delegate

       Up Vote for a delegate when there are locked lsk:

     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.



  > Cannot read properties of undefined (reading 'LSK')



When Cypress detects uncaught errors originating from your application it will automatically fail the current test.



This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.



https://on.cypress.io/uncaught-exception-from-application

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2520890

      at Array.reduce (<anonymous>)

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2520841

      at c (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2790943)

      at Generator._invoke (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2790731)

      at Generator.next (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2791372)

      at L (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2519192)

      at a (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2519395)

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2519454

      at new Promise (<anonymous>)



  2) Vote delegate

       Unlock balance:

     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.



  > Cannot read properties of undefined (reading 'LSK')



When Cypress detects uncaught errors originating from your application it will automatically fail the current test.



This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.



https://on.cypress.io/uncaught-exception-from-application

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2520890

      at Array.reduce (<anonymous>)

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2520841

      at c (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2790943)

      at Generator._invoke (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2790731)

      at Generator.next (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.vendor.1d4da06560221dbf2105.js:8:2791372)

      at L (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2519192)

      at a (https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2519395)

      at https://jenkins.lisk.com/test/lisk-desktop/PR-4048/bundle.app.a3fc59d73c8ed806aef2.js:1:2519454

      at new Promise (<anonymous>)
```
