### ISSUE TITLE
Application fails to load modules defined in lisk-api-client

### ISSUE THREAD

**Issue by soroushm** [LiskHQ/lisk-desktop#4520]
### Expected behavior
after @liskhq/lisk-client released version [6.0.0-alpha.32064](https://npm.lisk.com/-/web/detail/@liskhq/lisk-api-client/v/6.0.0-alpha.32064) wallet desktop complain about some of the packages is not exist in web browser, web-pack/babel should use browser export instead of node version

### Actual behavior
```js
index.js:6 Uncaught ReferenceError: require is not defined
    at ./node_modules/node-gyp-build/index.js (index.js:6:22)
    at __webpack_require__ (bootstrap:21:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/zeromq/lib/native.js (native.js:6:18)
    at __webpack_require__ (bootstrap:21:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/zeromq/lib/index.js (index.js:3:16)
    at __webpack_require__ (bootstrap:21:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/@liskhq/lisk-api-client/dist-node/ipc_channel.js (ipc_channel.js:7:18)
```

### Steps to reproduce
NPM install latest version of SDK 

### Which version(s) does this affect? (Environment, OS, etc...)
Version 3.0.0

**Comment by soroushm** [comment]
We used patch-package to fix the package for now but its need fix from the package
